"""release 0.3

Revision ID: 4c6266ee9629
Revises: 572bff1eda07
Create Date: 2015-11-04 13:32:55.145405

"""

# revision identifiers, used by Alembic.
revision = '4c6266ee9629'
down_revision = '572bff1eda07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sites', sa.Column('domain', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'sites', ['domain'])
    op.create_unique_constraint(None, 'sites', ['name'])
    op.drop_column('sites', 'desc')
    op.drop_column('sites', 'title')
    op.create_unique_constraint(None, 'users', ['display'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('sites', sa.Column('title', sa.VARCHAR(length=50), nullable=True))
    op.add_column('sites', sa.Column('desc', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'sites', type_='unique')
    op.drop_constraint(None, 'sites', type_='unique')
    op.drop_column('sites', 'domain')
    op.drop_table('site_settings')
    ### end Alembic commands ###
