"""release 0.4

Revision ID: 8d4ad8b835
Revises: 4c6266ee9629
Create Date: 2015-12-12 22:53:00.164205

"""

# revision identifiers, used by Alembic.
revision = '8d4ad8b835'
down_revision = '4c6266ee9629'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'sites', ['site_id'], ['id'])
    op.drop_index('name', table_name='sites')
    op.drop_column('sites', 'name')
    op.add_column('terms', sa.Column('site_id', sa.Integer(), nullable=True))
    op.drop_index('name', table_name='terms')
    op.create_foreign_key(None, 'terms', 'sites', ['site_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terms', type_='foreignkey')
    op.create_index('name', 'terms', ['name'], unique=True)
    op.drop_column('terms', 'site_id')
    op.add_column('sites', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('name', 'sites', ['name'], unique=True)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'site_id')
    ### end Alembic commands ###
